# Generated by Django 5.0.2 on 2024-10-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_today_catch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product_name',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_name',
            name='cut_type',
        ),
        migrations.RemoveField(
            model_name='today_catch',
            name='product_name',
        ),
        migrations.DeleteModel(
            name='Product_Type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Cut_type',
        ),
        migrations.DeleteModel(
            name='Product_name',
        ),
        migrations.DeleteModel(
            name='Today_Catch',
        ),
    ]
