# Generated by Django 5.0.2 on 2024-10-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_category_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('category_image', models.ImageField(upload_to='category_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Cut_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_type', models.CharField(max_length=200)),
                ('cut_image', models.ImageField(upload_to='cut_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200)),
                ('product_type_image', models.ImageField(upload_to='product_type_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.category')),
                ('cut_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.cut_type')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product_type'),
        ),
        migrations.CreateModel(
            name='Today_Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product_name')),
            ],
        ),
    ]
