# Generated by Django 5.0.2 on 2024-10-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_category_cut_type_product_type_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_name',
            name='cut_type',
        ),
        migrations.RemoveField(
            model_name='product_name',
            name='product_price',
        ),
        migrations.DeleteModel(
            name='Today_Catch',
        ),
    ]
