# Generated by Django 5.0.2 on 2024-10-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_product_name_cut_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_cut_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cut_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.cut_type')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product_name')),
            ],
        ),
        migrations.CreateModel(
            name='Today_Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_cut_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product_cut_price')),
            ],
        ),
    ]
