# Generated by Django 5.0.2 on 2024-10-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_today_catch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Today_Catch',
        ),
    ]
