# Generated by Django 5.0.2 on 2024-10-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_rename_product_cut_price_today_catch_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_owner_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_ownwer_name', models.CharField(max_length=200)),
                ('store_ownwer_email', models.EmailField(max_length=254, unique=True)),
                ('store_ownwer_password', models.CharField(max_length=200)),
                ('store_ownwer_mobile', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='today_catch',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product_name',
            name='category',
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.TextField(max_length=200)),
                ('store_location', models.TextField(max_length=200)),
                ('store_description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bussiness_hour', models.CharField(blank=True, max_length=100, null=True)),
                ('store_image', models.ImageField(blank=True, null=True, upload_to='store_images/')),
                ('store_ownwer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.store_owner_login')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_cut_price',
        ),
        migrations.DeleteModel(
            name='Today_Catch',
        ),
        migrations.DeleteModel(
            name='Product_name',
        ),
    ]
