# Generated by Django 5.0.2 on 2024-10-26 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_store_owner_login_remove_today_catch_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.category')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product_cut_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cut_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.cut_type')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product_name')),
            ],
        ),
        migrations.CreateModel(
            name='Today_Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product_cut_price')),
            ],
        ),
    ]
