# Generated by Django 5.0.2 on 2024-10-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_product_name_product_cut_price_today_catch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_name',
            name='product_available_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
