# Generated by Django 5.0.2 on 2024-10-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='category_image/'),
        ),
        migrations.AlterField(
            model_name='cut_type',
            name='cut_image',
            field=models.ImageField(upload_to='cut_image/'),
        ),
        migrations.AlterField(
            model_name='product_name',
            name='product_image',
            field=models.ImageField(upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='product_type_image',
            field=models.ImageField(upload_to='product_type_image/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
