# Generated by Django 5.0.2 on 2024-10-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cut_price',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='store_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store_owner_login',
            name='owner_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store_owner_login',
            name='owner_is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
