# Generated by Django 5.0.2 on 2024-10-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_store_city_alter_store_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
