# Generated by Django 5.0.2 on 2024-10-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_store_store_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='state',
        ),
    ]
