# Generated by Django 5.0.2 on 2024-10-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_remove_product_cut_price_mrp_product_name_mrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_description',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
