# Generated by Django 5.0.2 on 2024-10-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_remove_store_store_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_location',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
