# Generated by Django 5.0.2 on 2024-11-04 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_delete_product_cut_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_products',
            name='cut_type',
        ),
        migrations.RemoveField(
            model_name='store_products',
            name='product_price',
        ),
        migrations.CreateModel(
            name='Store_product_cutPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_todays_catch', models.BooleanField(default=True)),
                ('cut_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.cut_type')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.store_products')),
            ],
        ),
        migrations.DeleteModel(
            name='Today_Catch',
        ),
    ]
