# Generated by Django 5.0.2 on 2024-11-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_remove_store_products_cut_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_product_cutprice',
            name='is_default_cutprice',
            field=models.BooleanField(default=False),
        ),
    ]
