# Generated by Django 5.0.2 on 2024-11-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0028_store_product_cutprice_is_default_cutprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_owner_login',
            name='owner_is_active',
        ),
    ]
