# Generated by Django 5.0.2 on 2024-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_remove_store_owner_login_owner_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_product_cutprice',
            name='is_todays_catch',
            field=models.BooleanField(default=False),
        ),
    ]
