# Generated by Django 5.0.2 on 2024-11-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0031_store_product_cutprice_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_products',
            name='store_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.store'),
        ),
    ]
