# Generated by Django 5.0.2 on 2024-11-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_alter_store_products_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_product_cutprice',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='store_product_cutprice',
            name='is_todays_catch',
        ),
    ]
