# Generated by Django 5.0.2 on 2024-11-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_remove_store_product_cutprice_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_products',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store_products',
            name='is_todays_catch',
            field=models.BooleanField(default=False),
        ),
    ]
