# Generated by Django 5.0.2 on 2024-10-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_mobile_number', models.IntegerField()),
                ('user_address', models.TextField(max_length=200)),
            ],
        ),
    ]
