# Generated by Django 5.0.2 on 2024-10-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_product_name_product_available_quantity'),
        ('weesli_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Slot_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_slot_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_choosen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=100)),
                ('delivery_slot_date', models.DateTimeField()),
                ('user_location', models.CharField(max_length=200)),
                ('delivery_slot_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weesli_app.delivery_slot_time')),
                ('product_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.product_cut_price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weesli_app.user')),
            ],
        ),
    ]
