# Generated by Django 5.0.2 on 2024-11-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_remove_product_cut_price_cut_type_and_more'),
        ('weesli_app', '0002_delivery_slot_time_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='product_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.store_products'),
        ),
    ]
